name = "semantle"
main = "./src/server.ts"
compatibility_date = "2024-09-25"
account_id = "e24de7c361b035e990d2814691027093"
kv_namespaces = [{ binding = "KV", id = "c332d2251cbc47e3aef4071cb591b4c9" }]

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
